
[general]

	[general.hitboxes]
		hitbox_master_toggle = true

[hub]

	[hub.alerts]
		zombie_villager_alerts = true

	[hub.hitboxes]
		zombie_villager_hitbox = false
		graveyard_zombie_hitbox = false
		wolf_hitbox = true
		crypt_ghoul_hitbox = true
		golden_ghoul_hitbox = true
		old_wolf_hitbox = true

[crimson_isle]

	[crimson_isle.alerts]
		crimson_ghast_alerts = true
		vanquisher_alerts = true

	[crimson_isle.hitboxes]
		mutated_blaze_hitbox = true
		magma_cube_rider_hitbox = true
		flare_hitbox = false
		wither_spectre_hitbox = true
		vanquisher_hitbox = true
		kada_knight_hitbox = true
		flaming_spider_hitbox = true
		ghast_hitbox = true
		mushroom_bull_hitbox = true
		wither_skeleton_hitbox = true
		bezal_hitbox = true
		magma_cube_hitbox = false
		pack_magma_cube_hitbox = true
		blaze_hitbox = true

[farming_islands]

	[farming_islands.hitboxes]
		sheep_hitbox = false
		chicken_hitbox = false
		cow_hitbox = false
		pig_hitbox = false
		mushroom_cow_hitbox = false
		rabbit_hitbox = true

[mining_islands]

	[mining_islands.deep_caverns]
		miner_zombie_hitbox = false
		emerald_slime_hitbox = false
		miner_skeleton_hitbox = false
		redstone_pigman_hitbox = false
		lapis_zombie_hitbox = true

	[mining_islands.dwarven_mines]
		diamond_goblin_hitbox = true
		ice_walker_hitbox = true
		golden_goblin_hitbox = true
		powder_ghast_hitbox = true
		star_sentry_hitbox = true
		powder_ghast_alerts = true
		golden_goblin_alerts = true
		goblin_hitbox = true

["spider's_den"]

	["spider's_den".alerts]
		arachne_alerts = true
		broodmother_alerts = true

	["spider's_den".hitboxes]
		splitter_hitbox = false
		dasher_hitbox = false
		broodmother_hitbox = true
		arachne_hitbox = false
		slime_hitbox = true
		jockey_hitbox = true
		silverfish_hitbox = true
		arachne_mini_hitbox = false
		voracious_hitbox = false
		arachne_keeper_hitbox = true
		gravel_skeleton_hitbox = true

	["spider's_den".keeper_waypoints]
		keeper_waypoints = false

[misc]

	[misc.alerts]
		headless_horsemen_alerts = false

	[misc.nick_hider]
		nick_hider = ""
		nick_hider_toggle = false

	[misc.misc]
		drop_tracker = true

